name: cif-parse
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy>=2.3,<3
  - biotite>=1.6,<2
  - pandas>=2.3,<3
  - scipy>=1.17,<2
  - networkx>=3.6,<4
  - mmseqs2
  - usalign
  - biopython>=1.85,<2
  - pyhmmer>=0.11,<1
  - rdkit>=2026.03
  - sadie-antibody=2.0
  - pytest>=8,<9
  - pip:
      - -e .
